name: stock_sentinel_app
description: "金融哨兵 — Financial Sentinel"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  web_socket_channel: ^3.0.3
  provider: ^6.1.5+1
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  fl_chart: ^0.70.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
